name: Bug report
description: Report a potential bug within CMC Mod Manager
labels: ["bug"]
assignees:
  - Inferno214221
body:
  - type: markdown
    attributes:
      value: |
        Please describe the bug and include as much information as possible.

  - type: dropdown
    id: version
    attributes:
      label: CMC Mod Manager Version
      description: What version of CMC Mod Manager are you using? Have you tried the latest version?
      options:
        - v3.2.1
        - v3.2.0
        - v3.1.2
        - v3.1.1
        - v3.1.0
        - Older (why?)
    validations:
      required: true

  - type: dropdown
    id: build
    attributes:
      label: CMC Mod Manager Build
      description: Which build if CMC Mod Manager are you using?
      options:
        - Windows
        - Windows (32-bit)
        - Linux
        - Linux (deb)
        - Linux (rpm)

  - type: textarea
    id: issue
    attributes:
      label: Description of the Issue
      description: Provide a clear and informative description of the bug.
      placeholder: "Describe what went wrong..."
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Where does this issue occur?
      description: Is the issue within CMC Mod Manager itself, or within CMC+ as a result of CMC Mod Manager?
      options:
        - CMC Mod Manager
        - CMC+ but caused by CMC Mod Manager
        - Unsure
    validations:
      required: true

  - type: input
    id: frequency
    attributes:
      label: Frequency
      description: How frequently does the issue occur? (e.g. Every time I install a character / occasionally during downloads)
      placeholder: "Frequency of occurrence"

  - type: input
    id: mod
    attributes:
      label: Specific Mod Trigger
      description: If the issue is related to a specific mod, please provide its name.
      placeholder: "Name of the mod"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Copy any notable errors from the developer console (Ctrl+Shift+I).
      placeholder: "Paste error logs here"
