name: Feature request
description: Suggest an idea for CMC Mod Manager
labels: ["feature"]
assignees:
  - Inferno214221
body:
  - type: markdown
    attributes:
      value: |
        Please provide a detailed description of the feature you would like, after considering the following checklist.

  - type: checkboxes
    id: considerations
    attributes:
      label: Considerations
      description: Before submitting, please confirm you have considered these points.
      options:
        - label: I have checked whether this feature is already available in CMC Mod Manager.
        - label: I have checked whether this feature can be implemented without changes to the mod format defined by CMC+.
        - label: I have checked whether this feature is already planned or overlaps with any existing planned features.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature you would like.
      placeholder: "Describe your idea in detail..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        💡 **Tip:** Feel free to fork the project and open a pull request if you are willing to implement the feature yourself!
