name: Build With Electron Forge
run-name: Build With Electron Forge
on: [push, workflow_dispatch]

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Node Dependencies
        run: npm i
      - name: Electron Forge Build
        run: npm run make -- --platform win32 --targets @electron-forge/maker-squirrel
      
      - name: Zip Output
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: './cmc-mod-manager-windows.zip'
          path: './out/cmcmodmanager-win32-x64'
      
      - name: Upload Zip For Release
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows
          path: './cmc-mod-manager-windows.zip'
      
      - name: Electron Forge Build 32 bit
        run: npm run make -- --platform win32 --targets @electron-forge/maker-squirrel --arch=ia32
      
      - name: Zip Output
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: './cmc-mod-manager-windows-32.zip'
          path: './out/cmcmodmanager-win32-ia32'
      
      - name: Upload Zip For Release
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows-32
          path: './cmc-mod-manager-windows-32.zip'

  ubuntu-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Node Dependencies
        run: npm i
      - name: Electron Forge Build
        run: npm run make -- --platform linux --targets @electron-forge/maker-deb
        
      - name: Zip Output
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'cmc-mod-manager-linux.zip'
          path: './out/cmcmodmanager-linux-x64'
        
      - name: Upload Zip For Release
        uses: actions/upload-artifact@v3.1.2
        with:
          name: linux
          path: './cmc-mod-manager-linux.zip'

  make-release:
    runs-on: ubuntu-latest
    
    if: ${{ always() }}
    needs: [windows-build, ubuntu-build]
    permissions:
      contents: write
    
    steps:
      - name: Retrieve Windows Build Output
        uses: actions/download-artifact@v3
        with:
          name: windows
      - name: Retrieve Windows Build Output
        uses: actions/download-artifact@v3
        with:
          name: windows-32
          
      - name: Retrieve Linux Build Output 
        uses: actions/download-artifact@v3
        with:
          name: linux
          
      - run: ls -l
      
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: auto
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make Auto Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: auto
          tag_prefix: ""
      
      - name: Make A Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./cmc-mod-manager-windows.zip,./cmc-mod-manager-windows-32.zip,cmc-mod-manager-linux.zip"
          tag: auto
          prerelease: true
          makeLatest: false
